import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Router, useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

export default function Home({users}) {
  const router=useRouter()
  const handleckick =()=>{
    router.push("/profile");
    //router.replace("/profile")...it will replace the browser stack
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {/* <Image  src="https://images.unsplash.com/photo-1523800378286-dae1f0dae656?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1076&q=80" alt="Vercel Logo" width={72} height={16}></Image> */}
        <div>
          <Link href={"/posts"}>
          <a> <h2>View PostList</h2> </a>
          </Link>
          
        </div>
        <Image src="/banner.jpg" alt="Vercel Logo" width={720} height={160}></Image>
        <button onClick={handleckick}> Programitaclly go to Profile page</button>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
       <div className='homemap'>
        {
          users.map(e=>{
            return <div key={e.id} style={{"padding":"10px"}}> {e.username}</div>
          })
        }
       </div>
        

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(){
  const response= await fetch(`https://jsonplaceholder.typicode.com/users`)

  const data = await response.json();
  // console.log(data)
 return {
  props:{
    users:data,
  }
 }
}

